export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
export const HIDE_TRANSACTION_MODAL = "CLOSE_TRANSACTION";
export const SHOW_TRANSACTION_MODAL = "SHOW_TRANSACTION";
